# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Programming\youtube_embed_to_link\YoutubeEmbedToLinkGui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(923, 549)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.copiedLabel = QtWidgets.QLabel(self.centralwidget)
        self.copiedLabel.setEnabled(True)
        self.copiedLabel.setStyleSheet("color: rgba(0, 255, 0, 255);")
        self.copiedLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.copiedLabel.setObjectName("copiedLabel")
        self.gridLayout.addWidget(self.copiedLabel, 9, 4, 1, 1)
        self.edited = QtWidgets.QTextEdit(self.centralwidget)
        self.edited.setObjectName("edited")
        self.gridLayout.addWidget(self.edited, 7, 4, 1, 1)
        self.copyPasted = QtWidgets.QCheckBox(self.centralwidget)
        self.copyPasted.setObjectName("copyPasted")
        self.gridLayout.addWidget(self.copyPasted, 8, 2, 1, 1)
        self.deleteAfterCopied = QtWidgets.QCheckBox(self.centralwidget)
        self.deleteAfterCopied.setObjectName("deleteAfterCopied")
        self.gridLayout.addWidget(self.deleteAfterCopied, 9, 2, 1, 1)
        self.copyButton = QtWidgets.QPushButton(self.centralwidget)
        self.copyButton.setObjectName("copyButton")
        self.gridLayout.addWidget(self.copyButton, 8, 4, 1, 1)
        self.original = QtWidgets.QTextEdit(self.centralwidget)
        self.original.setObjectName("original")
        self.gridLayout.addWidget(self.original, 7, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 4, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setMinimumSize(QtCore.QSize(10, 0))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.addTagButton = QtWidgets.QPushButton(self.centralwidget)
        self.addTagButton.setObjectName("addTagButton")
        self.gridLayout_2.addWidget(self.addTagButton, 3, 1, 1, 1)
        self.addGroupButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addGroupButton.sizePolicy().hasHeightForWidth())
        self.addGroupButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.addGroupButton.setFont(font)
        self.addGroupButton.setIconSize(QtCore.QSize(2, 2))
        self.addGroupButton.setAutoDefault(False)
        self.addGroupButton.setDefault(False)
        self.addGroupButton.setFlat(False)
        self.addGroupButton.setObjectName("addGroupButton")
        self.gridLayout_2.addWidget(self.addGroupButton, 12, 1, 1, 3)
        self.removeTagButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeTagButton.setObjectName("removeTagButton")
        self.gridLayout_2.addWidget(self.removeTagButton, 3, 3, 1, 1)
        self.editTagButton = QtWidgets.QPushButton(self.centralwidget)
        self.editTagButton.setObjectName("editTagButton")
        self.gridLayout_2.addWidget(self.editTagButton, 3, 2, 1, 1)
        self.removeRuleButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeRuleButton.setObjectName("removeRuleButton")
        self.gridLayout_2.addWidget(self.removeRuleButton, 8, 3, 1, 1)
        self.editRuleButton = QtWidgets.QPushButton(self.centralwidget)
        self.editRuleButton.setObjectName("editRuleButton")
        self.gridLayout_2.addWidget(self.editRuleButton, 8, 2, 1, 1)
        self.editOutputButton = QtWidgets.QPushButton(self.centralwidget)
        self.editOutputButton.setObjectName("editOutputButton")
        self.gridLayout_2.addWidget(self.editOutputButton, 10, 2, 1, 1)
        self.removeOutputButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeOutputButton.setObjectName("removeOutputButton")
        self.gridLayout_2.addWidget(self.removeOutputButton, 10, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 11, 1, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 9, 1, 1, 1)
        self.addRuleButton = QtWidgets.QPushButton(self.centralwidget)
        self.addRuleButton.setObjectName("addRuleButton")
        self.gridLayout_2.addWidget(self.addRuleButton, 8, 1, 1, 1)
        self.addOutputButton = QtWidgets.QPushButton(self.centralwidget)
        self.addOutputButton.setObjectName("addOutputButton")
        self.gridLayout_2.addWidget(self.addOutputButton, 10, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 923, 21))
        self.menubar.setObjectName("menubar")
        self.menuedti = QtWidgets.QMenu(self.menubar)
        self.menuedti.setObjectName("menuedti")
        MainWindow.setMenuBar(self.menubar)
        self.actionCopyEdited = QtWidgets.QAction(MainWindow)
        self.actionCopyEdited.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionCopyEdited.setObjectName("actionCopyEdited")
        self.menuedti.addAction(self.actionCopyEdited)
        self.menubar.addAction(self.menuedti.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Html Tag Replacer"))
        self.copiedLabel.setText(_translate("MainWindow", "Copied"))
        self.copyPasted.setText(_translate("MainWindow", "Copy edited version after pasting original"))
        self.deleteAfterCopied.setText(_translate("MainWindow", "Delete original version after copied"))
        self.copyButton.setText(_translate("MainWindow", "Copy"))
        self.label.setText(_translate("MainWindow", "Original"))
        self.label_2.setText(_translate("MainWindow", "Edited"))
        self.addTagButton.setText(_translate("MainWindow", "Add"))
        self.addGroupButton.setText(_translate("MainWindow", "Add Group"))
        self.removeTagButton.setText(_translate("MainWindow", "Remove"))
        self.editTagButton.setText(_translate("MainWindow", "Edit"))
        self.removeRuleButton.setText(_translate("MainWindow", "Remove"))
        self.editRuleButton.setText(_translate("MainWindow", "Edit"))
        self.editOutputButton.setText(_translate("MainWindow", "Edit"))
        self.removeOutputButton.setText(_translate("MainWindow", "Remove"))
        self.label_5.setText(_translate("MainWindow", "Tags To Replace:"))
        self.label_4.setText(_translate("MainWindow", "Output:"))
        self.addRuleButton.setText(_translate("MainWindow", "Add"))
        self.addOutputButton.setText(_translate("MainWindow", "Add"))
        self.label_3.setText(_translate("MainWindow", "Rules:"))
        self.menuedti.setTitle(_translate("MainWindow", "Edit"))
        self.actionCopyEdited.setText(_translate("MainWindow", "Copy Edited"))
        self.actionCopyEdited.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))

