# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Programming\youtube_embed_to_link\YoutubeEmbedToLinkGui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(923, 549)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.copiedLabel = QtWidgets.QLabel(self.centralwidget)
        self.copiedLabel.setEnabled(True)
        self.copiedLabel.setStyleSheet("color: rgba(0, 255, 0, 255);")
        self.copiedLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.copiedLabel.setObjectName("copiedLabel")
        self.gridLayout.addWidget(self.copiedLabel, 9, 4, 1, 1)
        self.edited = QtWidgets.QTextEdit(self.centralwidget)
        self.edited.setObjectName("edited")
        self.gridLayout.addWidget(self.edited, 7, 4, 1, 1)
        self.copyPasted = QtWidgets.QCheckBox(self.centralwidget)
        self.copyPasted.setObjectName("copyPasted")
        self.gridLayout.addWidget(self.copyPasted, 8, 2, 1, 1)
        self.deleteAfterCopied = QtWidgets.QCheckBox(self.centralwidget)
        self.deleteAfterCopied.setObjectName("deleteAfterCopied")
        self.gridLayout.addWidget(self.deleteAfterCopied, 9, 2, 1, 1)
        self.copyButton = QtWidgets.QPushButton(self.centralwidget)
        self.copyButton.setObjectName("copyButton")
        self.gridLayout.addWidget(self.copyButton, 8, 4, 1, 1)
        self.original = QtWidgets.QTextEdit(self.centralwidget)
        self.original.setObjectName("original")
        self.gridLayout.addWidget(self.original, 7, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 4, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setMinimumSize(QtCore.QSize(10, 0))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.addOutputButton = QtWidgets.QPushButton(self.centralwidget)
        self.addOutputButton.setObjectName("addOutputButton")
        self.gridLayout_2.addWidget(self.addOutputButton, 9, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("background-color: #ffffff;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.tagsToReplaceLayout = QtWidgets.QWidget()
        self.tagsToReplaceLayout.setGeometry(QtCore.QRect(0, 0, 349, 104))
        self.tagsToReplaceLayout.setStyleSheet("background-color: #ffffff;")
        self.tagsToReplaceLayout.setObjectName("tagsToReplaceLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tagsToReplaceLayout)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.tagsToReplaceLayout)
        self.gridLayout_2.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.addTagButton = QtWidgets.QPushButton(self.centralwidget)
        self.addTagButton.setObjectName("addTagButton")
        self.gridLayout_2.addWidget(self.addTagButton, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 7, 0, 1, 1)
        self.addRuleButton = QtWidgets.QPushButton(self.centralwidget)
        self.addRuleButton.setObjectName("addRuleButton")
        self.gridLayout_2.addWidget(self.addRuleButton, 6, 0, 1, 1)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setStyleSheet("background-color: #ffffff;")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.outputLayout = QtWidgets.QWidget()
        self.outputLayout.setGeometry(QtCore.QRect(0, 0, 349, 104))
        self.outputLayout.setObjectName("outputLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.outputLayout)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea_3.setWidget(self.outputLayout)
        self.gridLayout_2.addWidget(self.scrollArea_3, 8, 0, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setStyleSheet("")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.rulesLayout = QtWidgets.QWidget()
        self.rulesLayout.setGeometry(QtCore.QRect(0, 0, 349, 103))
        self.rulesLayout.setObjectName("rulesLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.rulesLayout)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_2.setWidget(self.rulesLayout)
        self.gridLayout_2.addWidget(self.scrollArea_2, 5, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(2, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 923, 21))
        self.menubar.setObjectName("menubar")
        self.menuedti = QtWidgets.QMenu(self.menubar)
        self.menuedti.setObjectName("menuedti")
        MainWindow.setMenuBar(self.menubar)
        self.actionCopyEdited = QtWidgets.QAction(MainWindow)
        self.actionCopyEdited.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionCopyEdited.setObjectName("actionCopyEdited")
        self.menuedti.addAction(self.actionCopyEdited)
        self.menubar.addAction(self.menuedti.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Html Tag Replacer"))
        self.copiedLabel.setText(_translate("MainWindow", "Copied"))
        self.copyPasted.setText(_translate("MainWindow", "Copy edited version after pasting original"))
        self.deleteAfterCopied.setText(_translate("MainWindow", "Delete original version after copied"))
        self.copyButton.setText(_translate("MainWindow", "Copy"))
        self.label.setText(_translate("MainWindow", "Original"))
        self.label_2.setText(_translate("MainWindow", "Edited"))
        self.label_5.setText(_translate("MainWindow", "Tags To Replace:"))
        self.label_3.setText(_translate("MainWindow", "Rules:"))
        self.addOutputButton.setText(_translate("MainWindow", "Add"))
        self.addTagButton.setText(_translate("MainWindow", "Add"))
        self.label_4.setText(_translate("MainWindow", "Output:"))
        self.addRuleButton.setText(_translate("MainWindow", "Add"))
        self.menuedti.setTitle(_translate("MainWindow", "Edit"))
        self.actionCopyEdited.setText(_translate("MainWindow", "Copy Edited"))
        self.actionCopyEdited.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))

