# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\PycharmProjects\HTML-Swapper\AddRuleDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(426, 258)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttons = QtWidgets.QDialogButtonBox(Dialog)
        self.buttons.setOrientation(QtCore.Qt.Horizontal)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttons.setCenterButtons(False)
        self.buttons.setObjectName("buttons")
        self.gridLayout.addWidget(self.buttons, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setVerticalSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.keyFrame = QtWidgets.QFrame(self.frame)
        self.keyFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.keyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.keyFrame.setObjectName("keyFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.keyFrame)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.keyFrame)
        self.label_2.setEnabled(True)
        self.label_2.setMinimumSize(QtCore.QSize(55, 0))
        self.label_2.setMaximumSize(QtCore.QSize(55, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.keyLineEdit = QtWidgets.QLineEdit(self.keyFrame)
        self.keyLineEdit.setEnabled(True)
        self.keyLineEdit.setMinimumSize(QtCore.QSize(310, 0))
        self.keyLineEdit.setMaximumSize(QtCore.QSize(310, 16777215))
        self.keyLineEdit.setObjectName("keyLineEdit")
        self.horizontalLayout_2.addWidget(self.keyLineEdit)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 10)
        self.gridLayout_2.addWidget(self.keyFrame, 4, 0, 1, 2)
        self.ruleTypeFrame = QtWidgets.QFrame(self.frame)
        self.ruleTypeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ruleTypeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ruleTypeFrame.setObjectName("ruleTypeFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ruleTypeFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.ruleTypeFrame)
        self.label.setMinimumSize(QtCore.QSize(55, 0))
        self.label.setMaximumSize(QtCore.QSize(55, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ruleTypeDropdown = QtWidgets.QComboBox(self.ruleTypeFrame)
        self.ruleTypeDropdown.setMinimumSize(QtCore.QSize(310, 0))
        self.ruleTypeDropdown.setMaximumSize(QtCore.QSize(310, 16777215))
        self.ruleTypeDropdown.setObjectName("ruleTypeDropdown")
        self.horizontalLayout.addWidget(self.ruleTypeDropdown)
        self.horizontalLayout.setStretch(1, 65)
        self.gridLayout_2.addWidget(self.ruleTypeFrame, 2, 0, 1, 2)
        self.trueOrFalseFrame = QtWidgets.QFrame(self.frame)
        self.trueOrFalseFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trueOrFalseFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trueOrFalseFrame.setObjectName("trueOrFalseFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.trueOrFalseFrame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.trueOrFalseFrame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.trueOrFalseDropdown = QtWidgets.QComboBox(self.trueOrFalseFrame)
        self.trueOrFalseDropdown.setObjectName("trueOrFalseDropdown")
        self.horizontalLayout_4.addWidget(self.trueOrFalseDropdown)
        self.horizontalLayout_4.setStretch(1, 3)
        self.gridLayout_2.addWidget(self.trueOrFalseFrame, 7, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 6, 0, 1, 1)
        self.valueFrame = QtWidgets.QFrame(self.frame)
        self.valueFrame.setEnabled(True)
        self.valueFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valueFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.valueFrame.setObjectName("valueFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.valueFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.valueFrame)
        self.label_3.setMinimumSize(QtCore.QSize(55, 0))
        self.label_3.setMaximumSize(QtCore.QSize(55, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.valueLineEdit = QtWidgets.QLineEdit(self.valueFrame)
        self.valueLineEdit.setMinimumSize(QtCore.QSize(310, 0))
        self.valueLineEdit.setMaximumSize(QtCore.QSize(310, 16777215))
        self.valueLineEdit.setObjectName("valueLineEdit")
        self.horizontalLayout_3.addWidget(self.valueLineEdit)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 10)
        self.gridLayout_2.addWidget(self.valueFrame, 3, 0, 1, 2)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttons.accepted.connect(Dialog.accept)
        self.buttons.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Rule"))
        self.label_2.setText(_translate("Dialog", "Key:"))
        self.label.setText(_translate("Dialog", "Rule Type:"))
        self.label_4.setText(_translate("Dialog", "Rule is:"))
        self.label_3.setText(_translate("Dialog", "Value:"))
        self.label_5.setText(_translate("Dialog", "Tag"))

