# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Programming\HTML-Swapper\GUI\YoutubeEmbedToLinkGui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(923, 548)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.edited = QtWidgets.QTextEdit(self.centralwidget)
        self.edited.setObjectName("edited")
        self.gridLayout.addWidget(self.edited, 7, 4, 1, 1)
        self.original = QtWidgets.QTextEdit(self.centralwidget)
        self.original.setObjectName("original")
        self.gridLayout.addWidget(self.original, 7, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 4, 1, 1)
        self.deleteAfterCopied = QtWidgets.QCheckBox(self.centralwidget)
        self.deleteAfterCopied.setObjectName("deleteAfterCopied")
        self.gridLayout.addWidget(self.deleteAfterCopied, 10, 2, 1, 1)
        self.copyPasted = QtWidgets.QCheckBox(self.centralwidget)
        self.copyPasted.setObjectName("copyPasted")
        self.gridLayout.addWidget(self.copyPasted, 9, 2, 1, 1)
        self.copiedLabel = QtWidgets.QLabel(self.centralwidget)
        self.copiedLabel.setEnabled(True)
        self.copiedLabel.setStyleSheet("color: rgba(0, 255, 0, 255);")
        self.copiedLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.copiedLabel.setObjectName("copiedLabel")
        self.gridLayout.addWidget(self.copiedLabel, 10, 4, 1, 1)
        self.convertCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.convertCheckBox.setChecked(True)
        self.convertCheckBox.setObjectName("convertCheckBox")
        self.gridLayout.addWidget(self.convertCheckBox, 8, 2, 1, 1)
        self.copyButton = QtWidgets.QPushButton(self.centralwidget)
        self.copyButton.setObjectName("copyButton")
        self.gridLayout.addWidget(self.copyButton, 8, 4, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setMinimumSize(QtCore.QSize(10, 0))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 923, 21))
        self.menubar.setObjectName("menubar")
        self.menuedti = QtWidgets.QMenu(self.menubar)
        self.menuedti.setObjectName("menuedti")
        MainWindow.setMenuBar(self.menubar)
        self.actionCopyEdited = QtWidgets.QAction(MainWindow)
        self.actionCopyEdited.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionCopyEdited.setObjectName("actionCopyEdited")
        self.menuedti.addAction(self.actionCopyEdited)
        self.menubar.addAction(self.menuedti.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Html Tag Replacer"))
        self.label.setText(_translate("MainWindow", "Original"))
        self.label_2.setText(_translate("MainWindow", "Edited"))
        self.deleteAfterCopied.setText(_translate("MainWindow", "Delete original version after copied"))
        self.copyPasted.setText(_translate("MainWindow", "Copy edited version after pasting original"))
        self.copiedLabel.setText(_translate("MainWindow", "Copied"))
        self.convertCheckBox.setText(_translate("MainWindow", "Convert"))
        self.copyButton.setText(_translate("MainWindow", "Copy"))
        self.menuedti.setTitle(_translate("MainWindow", "Edit"))
        self.actionCopyEdited.setText(_translate("MainWindow", "Copy Edited"))
        self.actionCopyEdited.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))

